<?php
/**
 * Implements hook_init().
 */
function fanta_init() {
  drupal_add_library('fanta', 'ie6-warning');
}

/**
 * Implements hook_library().
 */
function fanta_library() {
  global $base_path;
  
  $libraries['ie6-warning'] = array(
    'js' => array(
      drupal_get_path('module', 'fanta') . '/ie6/warning.js' => array('every_page' => TRUE),
      drupal_get_path('module', 'fanta') . '/fanta.js' => array('every_page' => TRUE),
      array('data' => array('fanta' => array('ie6Path' => $base_path . drupal_get_path('module', 'fanta') . '/ie6/')), 'type' => 'setting'),
    ),
    'css' => array(
      drupal_get_path('module', 'fanta') . '/fanta.css' => array('every_page' => TRUE),
    ),
  );
  
  return $libraries;
}