<?php
/**
 * Implements hook_init().
 */
function fanta_init() {
  if (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE 6.')) {
    drupal_add_library('fanta', 'ie6-warning');
  }
}

/**
 * Implements hook_library().
 */
function fanta_library() {
  $libraries['ie6-warning'] = array(
    'js' => array(
      drupal_get_path('module', 'fanta') . '/ie6/warning.js' => array('cache' => FALSE, 'preprocess' => FALSE),
      drupal_get_path('module', 'fanta') . '/fanta.js' => array('cache' => FALSE, 'preprocess' => FALSE),
      array('data' => array('fanta' => array('ie6Path' => drupal_get_path('module', 'fanta') . '/ie6/')), 'type' => 'setting'),
    ),
    'css' => array(
      drupal_get_path('module', 'fanta') . '/fanta.css' => array(),
    ),
  );
  
  return $libraries;
}