<?php

/**
 * @file sedermera_investor.module
 * Main module file for the Sedermera Investor module.
 */

/**
 * Implements hook_permission().
 */
function sedermera_investor_permission() {
  return array(
    'view investors' => array(
      'title' => t('View investors'),
      'description' => t('Access the administration list for investors.'),
    ),
    'administer investors' => array(
      'title' => t('Administer investors'),
      'description' => t('Add entities of any investor bundles.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sedermera_investor_menu() {
  $items['avtalsparter/skapa'] = array(
    'title' => 'Lägg till avtalspart',
    'page callback' => 'sedermera_investor_create_page',
    'access arguments' => array('administer investors'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
// function sedermera_investor_menu_alter(&$items) {
//   // Get the entity info for the investor entity type.
//   $investor_info = entity_get_info('investor');

//   // Iterate through the bundles.
//   foreach ($investor_info['bundles'] as $bundle_name => $bundle_info) {
//     // Change the delete link for every bundle to a regular menu callback in
//     // order to get rid of the tab.
//     $items["investor/{$bundle_name}/%eckentity/delete"]['type'] = MENU_CALLBACK;

//     // Change the title callback for every bundle in order to use the entity
//     // label.
//     $items["investor/{$bundle_name}/%eckentity"]['title callback'] = 'sedermera_investor_entity_page_title';
//     $items["investor/{$bundle_name}/%eckentity"]['title arguments'] = array(2);
//   }
// }

/**
 * Implements hook_views_api().
 */
function sedermera_investor_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'sedermera_investor') . '/views',
  );
}

/**
 * Title callback for the entity pages for investor bundles.
 */
function sedermera_investor_entity_page_title($entity) {
  // Return the label of the entity.
  return entity_label('investor', $entity);
}

/**
 * Implements hook_admin_paths_alter().
 */
function sedermera_investor_admin_paths_alter(&$paths) {
  // Don't treat the add forms for investor bundles as administrative pages, in
  // order to use the sites default theme rather than the administration theme.
  $paths['admin/structure/entity-type/investor/*/add'] = FALSE;
}

/**
 * Page callback for the investerare/skapa path.
 *
 * This will generate a page that looks like the node/add page.
 *
 * @see node_add_page()
 */
function sedermera_investor_create_page() {
  $items[] = array(
    'title' => 'Avtalspart Privat',
    'href' => "node/add/investor-private",
    'description' => 'Lägg till en ny privatperson.',
    'localized_options' => array(
      'query' => array('destination' => 'avtalsparter'),
    ),
  );

  $items[] = array(
    'title' => 'Avtalspart Bolag',
    'href' => "node/add/investor-company",
    'description' => 'Lägg till ett nytt bolag.',
    'localized_options' => array(
      'query' => array('destination' => 'avtalsparter'),
    ),
  );

  return theme('node_add_list', array('content' => $items));
}

/**
 * Implements hook_field_widget_form_alter().
 */
function sedermera_investor_field_widget_form_alter(&$element, &$form_state, $context) {
  // Disable access to the field_shared_temp field. This will hopefully be
  // managed automatically in the future. We'll disable it for now, just to make
  // sure that we avoid any confusion for the end user.
  if ($element['#field_name'] == 'field_shared_temp') {
    $element['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
// function sedermera_investor_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
//   // Alter the exposed form for the investor page and offer embed displays.
//   if (in_array($form['#id'], array('views-exposed-form-investors-page', 'views-exposed-form-investors-offer-embed'))) {
//     // Get the country values from the database. We'll use a regular DB Query in
//     // order to improve performance.
//     $available_countries = db_query("SELECT DISTINCT field_shared_address_country FROM {field_data_field_shared_address}")->fetchAllKeyed();

//     // Remove the options that aren't stored in the database.
//     $form['country']['#options'] = array_intersect_key($form['country']['#options'], $available_countries);

//     // Disable access to the country field and remove the label if the options
//     // are empty.
//     if (empty($form['country']['#options'])) {
//       $form['country']['#access'] = FALSE;
//       unset($form['#info']['filter-field_shared_address_country']);
//     }

//     // Get the industry values from the database. We'll use a regular DB Query
//     // here as well, for the same reason as above...
//     $available_industries = db_query("SELECT DISTINCT field_shared_industries_tid FROM {field_data_field_shared_industries}")->fetchAllKeyed();

//     // Remove the options that aren't stored in the database, and disable access
//     // to the field if the options are empty.
//     $form['industries']['#options'] = array_intersect_key($form['industries']['#options'], $available_industries);

//     // Disable access to the industries field and remove the label if the
//     // options are empty.
//     if (empty($form['industries']['#options'])) {
//       $form['industries']['#access'] = FALSE;
//       unset($form['#info']['filter-field_shared_industries_tid']);
//     }
//   }
// }

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_investor_form_eck__entity__form_add_investor_person_alter(&$form, &$form_state, $form_id) {
  if (!empty($_POST['lead_id'])) {
    $lead = entity_load_single('investor', $_POST['lead_id']);
    $wrapper = entity_metadata_wrapper('investor', $lead);

    $form['field_invest_pers_first_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_lead_first_name->value();
    $form['field_invest_pers_last_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_lead_last_name->value();
    $form['field_shared_email'][LANGUAGE_NONE][0]['email']['#default_value'] = $wrapper->field_shared_email->value();
    $form['field_shared_phone'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_shared_phone->value();
    $form['field_shared_cell'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_shared_cell->value();
    $form['field_shared_notes'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_shared_notes->value();

    $lead->publish = 1;
    $lead->save();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_investor_form_eck__entity__form_add_investor_company_alter(&$form, &$form_state, $form_id) {
  if (!empty($_POST['lead_id'])) {
    $lead = entity_load_single('investor', $_POST['lead_id']);
    $wrapper = entity_metadata_wrapper('investor', $lead);

    $form['field_invest_comp_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_lead_first_name->value() . " " . $wrapper->field_lead_last_name->value();
    $form['field_shared_email'][LANGUAGE_NONE][0]['email']['#default_value'] = $wrapper->field_shared_email->value();
    $form['field_shared_phone'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_shared_phone->value();
    $form['field_shared_cell'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_shared_cell->value();
    $form['field_shared_notes'][LANGUAGE_NONE][0]['value']['#default_value'] = $wrapper->field_shared_notes->value();

    $lead->publish = 1;
    $lead->save();
  }
}

/**
 * Implements hook_node_presave
 */
function sedermera_investor_node_presave($node) {
  if ($node->type == 'person') {
    if ($node->is_new) {
      global $user;

      $new_node = new stdClass();
      $new_node->title = $node->title . " ID kontroll";
      $new_node->type = "ctrl";
      node_object_prepare($new_node);
      $new_node->language = LANGUAGE_NONE;
      $new_node->uid = $user->uid;
      $new_node->status = 1;
      $new_node->promote = 0;
      $new_node->comment = 0;

      $new_node = node_submit($new_node);
      node_save($new_node);

      $node->field_user_id_ctrl[LANGUAGE_NONE][0]['target_id'] = $new_node->nid;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function sedermera_investor_form_investor_bolag_node_form_alter(&$form, &$form_state, $form_id) {
  if (!isset($form_state['node']->nid)) {
    $id = get_next_cust_id();
    $form['field_shared_cust_id'][LANGUAGE_NONE][0]['value']['#default_value'] = $id;
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function sedermera_investor_form_investor_privat_node_form_alter(&$form, &$form_state, $form_id) {
  if (!isset($form_state['node']->nid)) {
    $id = get_next_cust_id();
    $form['field_shared_cust_id'][LANGUAGE_NONE][0]['value']['#default_value'] = $id;
  }
}

/**
 * Generate the next incremental customer id
 * @return Incremented customer id.
 */
function get_next_cust_id() {
  $result = db_query("SELECT field_shared_cust_id_value AS id FROM field_data_field_shared_cust_id ORDER BY field_shared_cust_id_value DESC")->fetchAssoc();

  preg_match('!\d+!', $result['id'], $matches);
  $n2 = str_pad($matches[0] + 1, 3, 0, STR_PAD_LEFT);

  return 'A' . $n2;
}


/**
 * Implements hook_node_validate().
 */
function sedermera_investor_node_validate($node, $form, &$form_state) {
  if ($form_state['values']['type'] == 'person') {
    if ($form_state['values']['field_user_lead'][LANGUAGE_NONE][0]['value'] == 0) {
      if ($form_state['values']['field_user_mail'][LANGUAGE_NONE][0]['email'] == '') {
        form_set_error('field_user_mail', t('Mejl address måste fyllas i.'));
      }
      if ($form_state['values']['field_user_ssn'][LANGUAGE_NONE][0]['value'] == '') {
        form_set_error('field_user_ssn', t('Personnummer måste fyllas i.'));
      }
      $pnbr = $node->field_user_ssn[LANGUAGE_NONE][0]['value'];

      if (preg_match("/^\d{6}-\d{4}/", $pnbr) !== 1) {
        form_set_error('field_user_ssn', t('Person number not valid.'));
      }

      if (isset($node->nid)) {
        if (!person_nbr_is_same($pnbr, $node->nid) && person_nbr_exists($pnbr)) {
          form_set_error('field_user_ssn', t('Person number already in use.'));
        }
      }
      else {
        if (person_nbr_exists($pnbr)) {
          form_set_error('field_user_ssn', t('Person number already in use.'));
        }
      }
    }
  }
  if ($form_state['values']['type'] == 'investor_bolag') {
    $org_nbr = $node->field_investor_comp_org_nbr[LANGUAGE_NONE][0]['value'];
    $cust_id = $form_state['values']['field_shared_cust_id'][LANGUAGE_NONE][0]['value'];

    if (preg_match("/^\d{6}-\d{4}/", $org_nbr) !== 1) {
      form_set_error('field_investor_comp_org_nbr', t('Organisation number not valid.'));
    }

    if (isset($node->nid)) {
      if (!org_nbr_is_same($org_nbr, $node->nid) && org_nbr_exists($org_nbr)) {
        form_set_error('field_investor_comp_org_nbr', t('Organisation number already in use.'));
      }
      if (!cust_id_is_same($cust_id, $node->nid) && cust_id_exists($cust_id)) {
        form_set_error('field_investor_comp_org_nbr', t('Organisation number already in use.'));
      }
    }
    else {
      if (org_nbr_exists($org_nbr)) {
        form_set_error('field_investor_comp_org_nbr', t('Organisation number already in use.'));
      }
      if (cust_id_exists($cust_id)) {
        form_set_error('field_shared_cust_id', t('Customer id already exists, please resave use id: ' . get_next_cust_id()));
      }
    }
  }
  if ($form_state['values']['type'] == 'investor_privat') {
    $cust_id = $form_state['values']['field_shared_cust_id'][LANGUAGE_NONE][0]['value'];
    if (isset($node->nid)) {
      if (!cust_id_is_same($cust_id, $node->nid) && cust_id_exists($cust_id)) {
        form_set_error('field_investor_comp_org_nbr', t('Organisation number already in use.'));
      }
    }
    else {
      if (cust_id_exists($cust_id)) {
        form_set_error('field_shared_cust_id', t('Customer id already exists, please resave use id: ' . get_next_cust_id()));
      }
    }
  }
}

/**
 * Checks if customer id already exist in the system
 * @param  $cust_id Customer id to check for
 * @return boolean true if exists else false
 */
function cust_id_exists($cust_id) {
  $result = db_query("SELECT COUNT(*) AS count FROM field_data_field_shared_cust_id WHERE field_shared_cust_id_value = :id", array(':id' => $cust_id))->fetchAll();

  return ($result[0]->count > 0) ? TRUE : FALSE;
}

/**
 * Checks if person number has been changed from the existing in the system
 * @param  $pnbr Person number to check for
 * @param  $nid  The node to check on
 * @return boolean true if no change else false
 */
function cust_id_is_same($custid, $nid) {
  $cust_id_is_same = db_query("SELECT COUNT(*) AS count FROM field_data_field_shared_cust_id WHERE field_shared_cust_id_value = :custid AND entity_id = :nid", array(':custid' => $custid, ':nid' => $nid))->fetchAssoc();

  return $cust_id_is_same['count'] ? TRUE : FALSE;
}

/**
 * Checks if person number already exists in the system
 * @param  $pnbr The person number to check for
 * @return boolean true if exists else false
 */
function person_nbr_exists($pnbr) {
  $pnbr_exists = db_query("SELECT COUNT(*) AS count FROM field_data_field_user_ssn WHERE field_user_ssn_value = :pnbr", array(':pnbr' => $pnbr))->fetchAssoc();

  return $pnbr_exists['count'] ? TRUE : FALSE;
}

/**
 * Checks if person number has been changed from the existing in the system
 * @param  $pnbr Person number to check for
 * @param  $nid  The node to check on
 * @return boolean true if no change else false
 */
function person_nbr_is_same($pnbr, $nid) {
  $pnbr_is_same = db_query("SELECT COUNT(*) AS count FROM field_data_field_user_ssn WHERE field_user_ssn_value = :pnbr AND entity_id = :nid", array(':pnbr' => $pnbr, ':nid' => $nid))->fetchAssoc();

  return $pnbr_is_same['count'] ? TRUE : FALSE;
}

/**
 * Checks if organisation number already exists in the system
 * @param  $org_nbr The organisation number to check for
 * @return boolean true if exists else false
 */
function org_nbr_exists($org_nbr) {
  $org_nbr_exists = db_query("SELECT COUNT(*) AS count FROM field_data_field_investor_comp_org_nbr WHERE field_investor_comp_org_nbr_value = :org_nbr", array(':org_nbr' => $org_nbr))->fetchAssoc();

  return $org_nbr_exists['count'] ? TRUE : FALSE;
}

/**
 * Checks if organisation number has been changed from the existing in the system
 * @param  $org_nbr Person number to check for
 * @param  $nid  The node to check on
 * @return boolean true if no change else false
 */
function org_nbr_is_same($org_nbr, $nid) {
  $org_nbr_is_same = db_query("SELECT COUNT(*) AS count FROM field_data_field_investor_comp_org_nbr WHERE field_investor_comp_org_nbr_value = :org_nbr AND entity_id = :nid", array(':org_nbr' => $org_nbr, ':nid' => $nid))->fetchAssoc();

  return $org_nbr_is_same['count'] ? TRUE : FALSE;
}
