version: '2'

services:

  # MariaDB container.
  mariadb:
    image: wodby/mariadb:10.1-2.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: odddrupal
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ~/data/odddrupal:/var/lib/mysql
    ports:
      - 33060:3306

  # PHP container.
  php:
    image: wodby/drupal-php:7.1-2.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: odddrupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
    volumes:
      - ./:/var/www/html:cached

  # Nginx container.
  nginx:
    image: wodby/drupal-nginx:7-1.13
    depends_on:
      - php
    environment:
      NGINX_SERVER_NAME: odddrupal
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    ports:
      - 8000:80

  # Mailhog container.
  mailhog:
    image: mailhog/mailhog
