<?php

/**
 * @file sedermera_offer.module
 * Main module file for the Sedermera Offer module.
 */

/**
 * Implements hook_menu().
 */
function sedermera_transaction_menu() {
  $items['node/%/intressenter'] = array(
    'title' => 'Intressenter',
    'page callback' => 'sedermera_transaction_intresent',
    'page arguments' => array(1),
    'access callback' => 'sedermera_transaction_offer_access',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;
}

/**
 * Checks if the current node should have access to intressent list
 * @return boolean TRUE if ok else FALSE
 */
function sedermera_transaction_offer_access() {
  // Load node
  $node = node_load(arg(1));

  // Check if node is of type offer
  if ($node->type === 'offer') {
    return TRUE;
  }

  return FALSE;
}

/**
 * Render intresent table
 */
function sedermera_transaction_intresent() {
  $transactions = get_transactions(arg(1));

  if (!empty($transactions)) {
    $offer = node_load(arg(1));

    $fe_sign = !empty($offer->field_offer_type_fe_sign);
    $fe_warr = !empty($offer->field_offer_type_fe_warrant);
    $le_sign = !empty($offer->field_offer_type_le_sign);
    $le_warr = !empty($offer->ffield_offer_type_le_warrant);
    $pp_sign = !empty($offer->field_offer_type_pp_sign);
    $re_sign = !empty($offer->field_offer_type_re_sign);
    $bl_sum  = !empty($offer->field_offer_type_bl_sum);
    $bp_sum  = !empty($offer->field_offer_type_bp_sum);

    $header = array(
      array('class' => array('table-head', 'logo-head')),
      array('data' => 'Kontaktperson', 'class' => array('table-head')),
      array('data' => '', 'class' => array('table-head')),
    );

    if ($fe_sign) {
      $header[] = array(
        'data' => 'Teckningsförbindelse',
        'class' => array('table-head')
      );
    }
    if ($fe_warr) {
      $header[] = array(
        'data' => 'Garantiåtagande',
        'class' => array('table-head')
      );
    }
    if ($le_sign) {
      $header[] = array(
        'data' => 'Teckningsförbindelse',
        'class' => array('table-head')
      );
    }
    if ($le_warr) {
      $header[] = array(
        'data' => 'Garantiåtagande',
        'class' => array('table-head')
      );
    }
    if ($pp_sign) {
      $header[] = array(
        'data' => 'Teckningsförbindelse',
        'class' => array('table-head')
      );
    }
    if ($re_sign) {
      $header[] = array(
        'data' => 'Teckningsförbindelse',
        'class' => array('table-head')
      );
    }
    if ($bl_sum) {
      $header[] = array(
        'data' => 'Brygglån',
        'class' => array('table-head')
      );
    }
    if ($bp_sum) {
      $header[] = array(
        'data' => 'Blockpost',
        'class' => array('table-head')
      );
    }

    $header[] = array(
      'data' => 'Summa',
      'class' => array('table-head')
    );

    $header[] = array(
      'data' => '',
      'class' => array('table-head')
    );

    $header[] = array(
      'data' => 'Till kontroll',
      'class' => array('table-head')
    );

    $rows = array();
    foreach ($transactions as $transaction_nid) {
      $transaction = node_load($transaction_nid);

      $person = node_load($transaction->field_transaction_person[LANGUAGE_NONE][0]['target_id']);

      $results = db_query("SELECT n.nid AS nid, n.title AS name FROM node AS n INNER JOIN field_data_field_shared_cont_pers AS u ON (n.nid = u.entity_id) WHERE u.field_shared_cont_pers_target_id = :tid", array(':tid' => $person->nid))->fetchAll();

      if (empty($results)) {
        $drop_down = array(
          '#prefix' => 'Inga avtalsparter',
          );
      }
      else {
        $options = array(
            '#prefix' => '<div class="dropdown">',
            '#suffix' => '</div>',
          );

        $partner_types = array();

        foreach ($results as $value) {
          $partner_types[$value->nid] = $value->name;
        }

        foreach ($partner_types as $key => $title) {
          $tf = FALSE;
          $attributes = array();

          foreach ($transaction->field_transaction_investor[LANGUAGE_NONE] as $value) {
            $res = db_query("SELECT COUNT(*) AS tf FROM {field_data_field_transaction_ap_ap} WHERE entity_id = :eid AND field_transaction_ap_ap_target_id = :tid", array(':eid' => $value['target_id'], ':tid' => $key))->fetchAssoc();

            if ($res['tf'] == 1) {
              $tf = TRUE;
              $attributes = array('checked' => 'checked');
              break;
            }
          }

          $options[$key] = array(
            '#type' => 'checkbox',
            '#title' => $title,
            '#default_value' => $tf,
            '#attributes' => $attributes,
            '#disabled' => $tf,
          );
        }

        $drop_down = array(
          '#type' => 'checkboxes',
          '#prefix' => '<div class="select-container partners">',
          '#suffix' => '</div>',
          'select' => array(
            '#markup' => '<div class="select">Avtalspartners</div>',
          ),
          'options' => $options,

        );
      }

      $rows[] = array(
        array(
          'class' => 'logo-head',
        ),
        array(
          'data' => $person->title,
        ),
        array(
          'data' => $drop_down,
        ),
      );

      $row = count($rows) - 1;

      $sum = 0;

      if ($fe_sign) {
        $sum += $transaction->field_transaction_fe_sign[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_fe_sign',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));
        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($fe_warr) {
        $sum += $transaction->field_transaction_fe_warant[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_fe_warant',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($le_sign) {
        $sum += $transaction->field_transaction_le_sign[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_le_sign',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($le_warr) {
        $sum += $transaction->field_transaction_le_warrant[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_le_warrant',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($pp_sign) {
        $sum += $transaction->field_transaction_pp_sign[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_pp_sign',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($re_sign) {
        $sum += $transaction->field_transaction_re_sign[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_re_sign',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($bl_sum) {
        $sum += $transaction->field_transaction_bridging[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_bridging',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }
      if ($bp_sum) {
        $sum += $transaction->field_transaction_block[LANGUAGE_NONE][0]['value'];
        $field = field_view_field('node', $transaction, 'field_transaction_block',
              array(
                'label'=>'hidden',
                'settings' => array(
                  'thousand_separator' => '\'',
                ),
              ));

        $rows[$row][] = array(
          'data' => render($field),
        );
      }

      $sum = number_format($sum, 0, "", "'");

      $rows[$row][] = array(
        'data' => $sum . " :-",
      );

      $field = field_view_field('node', $person, 'field_user_id_ctrl',
            array(
              'label'=>'hidden',
              'type' => 'sedermera_verification_status',
            ));

      $rows[$row][] = array(
        'data' => render($field),
      );

      $done = 0;
      $count = 0;

      foreach ($transaction->field_transaction_investor as $value) {
        foreach ($value as $val) {
          $result = db_query("SELECT field_transaction_ap_ctrl_value AS value FROM {field_data_field_transaction_ap_ctrl} WHERE entity_id = :eid", array(':eid' => $val['target_id']))->fetchAll();
          $done += $result[0]->value;
          $count++;
        }
      }

      if ($done == 0 && $count == 0) {
        $next = "0 valda";
      }
      else {
        $next = $done ."/" . $count . " klara";
      }

      $rows[$row][] = array(
        'data' => $next,
      );

      $fe_sign_sum = 0;
      $fe_warr_sum = 0;
      $le_sign_sum = 0;
      $le_warr_sum = 0;
      $pp_sign_sum = 0;
      $re_sign_sum = 0;
      $bl_sum      = 0;
      $bp_sum      = 0;
      $total_sum   = 0;

      // AP rows
      foreach ($transaction->field_transaction_investor as $value) {
        foreach ($value as $val) {
          $transaction_ap = node_load($val['target_id']);

          $ap = node_load($transaction_ap->field_transaction_ap_ap[LANGUAGE_NONE][0]['target_id']);

          $rows[] = array(
            array(
              'class' => 'logo-head',
            ),
            array(
              'data' => $ap->title,
            ),
            array(
              'data' => '',
            ),
          );

          $row = count($rows) - 1;

          $sum = 0;

          if ($fe_sign) {
            $fe_sign_sum += $transaction_ap->field_transaction_ap_fe_sign[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_fe_sign[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_fe_sign',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($fe_warr) {
            $fe_warr_sum += $transaction_ap->field_transaction_ap_fe_warrant[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_fe_warrant[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_fe_warrant',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($le_sign) {
            $le_sign_sum += $transaction_ap->field_transaction_ap_le_sign[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_le_sign[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_le_sign',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($le_warr) {
            $le_warr_sum += $transaction_ap->field_transaction_ap_le_warrant[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_le_warrant[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_le_warrant',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($pp_sign) {
            $pp_sign_sum += $transaction_ap->field_transaction_ap_pp_sign[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_pp_sign[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_pp_sign',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($re_sign) {
            $re_sign_sum += $transaction_ap->field_transaction_ap_re_sign[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_re_sign[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_re_sign',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($bl_sum) {
            $bl_sum += $transaction_ap->field_transaction_ap_bridging[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_bridging[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_bridging',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }
          if ($bp_sum) {
            $bp_sum += $transaction_ap->field_transaction_ap_block[LANGUAGE_NONE][0]['value'];
            $sum += $transaction_ap->field_transaction_ap_block[LANGUAGE_NONE][0]['value'];
            $field = field_view_field('node', $transaction_ap, 'field_transaction_ap_block',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));
            $rows[$row][] = array(
              'data' => render($field),
            );
          }

          $total_sum += $sum;

          $sum = number_format($sum, 0, "", "'");

          $rows[$row][] = array(
            'data' => $sum . " :-",
          );

          $ap_view_full = node_view($ap);

          $rows[$row][] = array(
            'data' => render($ap_view_full['verification_status']),
          );


          if ($transaction_ap->field_transaction_ap_ctrl[LANGUAGE_NONE][0]['value']) {
            $rows[$row][] = array(
              'data' => '<span></span> kontrollera',
            );
          }
          else {
            $to_ctrl = field_view_field('node', $transaction_ap, 'field_transaction_ap_ctrl',
                  array(
                    'label'=>'hidden',
                    'type' => 'editable',
                  ));

            $rows[$row][] = array(
              'data' => render($to_ctrl),
            );
          }
        }
      }

      // Sum row
      $rows[] = array(
        array(
          'data' => '',
        ),
        array(
          'data' => '',
        ),
        array(
          'data' => '<strong>Summa kontaktperson:</strong>',
        ),
      );

      $row = count($rows) - 1;

      if ($fe_sign) {
        $rows[$row][] = array(
          'data' => number_format($fe_sign_sum, 0, "", "'") . ' :-',
        );
      }
      if ($fe_warr) {
        $rows[$row][] = array(
          'data' => number_format($fe_warr_sum, 0, "", "'") . ' :-',
        );
      }
      if ($le_sign) {
        $rows[$row][] = array(
          'data' => number_format($le_sign_sum, 0, "", "'") . ' :-',
        );
      }
      if ($le_warr) {
        $rows[$row][] = array(
          'data' => number_format($le_warr_sum, 0, "", "'") . ' :-',
        );
      }
      if ($pp_sign) {
        $rows[$row][] = array(
          'data' => number_format($pp_sign_sum, 0, "", "'") . ' :-',
        );
      }
      if ($re_sign) {
        $rows[$row][] = array(
          'data' => number_format($re_sign_sum, 0, "", "'") . ' :-',
        );
      }
      if ($bl_sum) {
        $rows[$row][] = array(
          'data' => number_format($bl_sum, 0, "", "'") . ' :-',
        );
      }
      if ($bp_sum) {
        $rows[$row][] = array(
          'data' => number_format($bp_sum, 0, "", "'") . ' :-',
        );
      }

      $rows[$row][] = array(
        'data' => number_format($total_sum, 0, "", "'") . ' :-',
      );

      $rows[$row][] = array(
        'data' => '',
      );

      $rows[$row][] = array(
        'data' => '',
      );
    }

    // Create table.
    return array(
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $rows,
      '#prefix' => '<div class="table-wrapper">',
      '#suffix' => '</div>',
    );
  }
  else {
    drupal_set_title('Det finns inga transaktioner');
    return array(
      '#theme' => 'table',
      '#header' => array(),
      '#rows' => NULL,
      '#prefix' => '<div class="table-wrapper">',
      '#suffix' => '</div>',
    );
  }
}

/**
 * Get documents
 * @return entity loaded documents
 */
function get_transactions($nid) {
  $result = db_query("SELECT entity_id AS nid FROM {field_data_field_transaction_offer} WHERE field_transaction_offer_target_id = :nid", array(':nid' => $nid))->fetchAllAssoc('nid');

  return array_keys($result);
}
