<?php

/**
 * @file sedermera_core.module
 * Main module file for the Sedermera Core module.
 */

/**
 * Implements hook_menu_alter().
 */
function sedermera_core_menu_alter(&$items) {
  $items['node/%node/view']['title'] = 'Översikt';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_core_form_user_login_alter(&$form, &$form_state) {
  // Add links to the user login form which lets the user reset the password
  // and report a lost YubiKey.
  $form['links'] = array(
    '#theme' => 'links',
    '#links' => array(
      'password-reset' => array(
        'title' => 'Återställ bortglömt lösenord',
        'href' => 'user/password',
      ),
      'yubikey-lost' => array(
        'title' => 'Anmäl borttappad YubiKey',
        'href' => 'user/yubikey/lost',
      ),
    ),
    '#weight' => 500,
  );
}
