<?php

/**
 * @file sedermera_core.module
 * Main module file for the Sedermera Core module.
 */

/**
 * Implements hook_menu_alter().
 */
function sedermera_core_menu_alter(&$items) {
  $items['node/%node/view']['title'] = 'Översikt';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_core_form_user_login_alter(&$form, &$form_state) {
  // Add links to the user login form which lets the user reset the password
  // and report a lost YubiKey.
  $form['reset-links'] = array(
    '#theme' => 'links',
    '#links' => array(
      'password-reset' => array(
        'title' => 'Återställ bortglömt lösenord',
        'href' => 'user/password',
      ),
      'yubikey-lost' => array(
        'title' => 'Anmäl borttappad YubiKey',
        'href' => 'user/yubikey/lost',
      ),
    ),
    '#weight' => 501,
  );

  // Set the weight for the action buttons in order to guarantee the appropriate
  // order.
  $form['actions']['#weight'] = 500;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_core_form_yubikey_lost_alter(&$form, &$form_state) {
  // Don't enable the password field when reporting a lost YubiKey. There are
  // two reasons for this:
  // 1. The validation doesn't work since the YubiKey module queries the
  // database using the password in plain text.
  // 2. The user still needs to confirm this via a confirmation email.
  $form['yubikey_forgot_pass']['#type'] = 'value';
  $form['yubikey_forgot_pass']['#value'] = TRUE;
  $form['pass']['#access'] = FALSE;
}
