<?php
;$Id;

/**
 * @file
 *
 * creating an implementation for Drupal of the JavaScript code
 * found at http://code.google.com/p/sevenup/
 */

/**
 * Implementation of hook_menu().
 */
function sevenup_menu() {
  $items = array();
  $items['admin/settings/sevenup'] = array(
    'title' => 'Seven Up Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sevenup_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * create the admin settings form
 */
function sevenup_admin_settings_form() {
  $form = array();
  $options = array(
    'true' => t('Yes'),
    'false' => t('No'),
  );
  $form['sevenUp_enableClosing'] = array(
    '#title' => t('Enable Closing'),
    '#description' => t('Allow the users to close the box urguing them to upgrade.'),
    '#default_value' => variable_get('sevenUp_enableClosing', 'true'),
    '#type' => 'radios',
    '#options' => $options,
  );
  $form['sevenUp_enableQuitBuggingMe'] = array(
    '#title' => t('Enable "Quit Bugging Me"'),
    '#description' => t('Allow the users to opt for a cookie to be set to bypass the warning.'),
    '#default_value' => variable_get('sevenUp_enableQuitBuggingMe', 'true'),
    '#type' => 'radios',
    '#options' => $options,
  );
  $form['sevenUp_overlayColor'] = array(
    '#title' => t('Overlay Color'),
    '#default_value' => variable_get('sevenUp_overlayColor', '#000000'),
    '#type' => 'textfield',
  );
  $form['sevenUp_lightboxColor'] = array(
    '#title' => t('Light Box Color'),
    '#default_value' => variable_get('sevenUp_lightboxColor', '#ffffff'),
    '#type' => 'textfield',
  );
  $form['sevenUp_borderColor'] = array(
    '#title' => t('Border Color'),
    '#default_value' => variable_get('sevenUp_borderColor', '#6699ff'),
    '#type' => 'textfield',
  );
  $form['sevenUp_downloadLink'] = array(
    '#title' => t('What Browser Do you want to suggest?'),
    '#description' => t('A link will be displayed for the user to upgrade their browser. Which browser would you like to recommend? If you choose Internet Explorer and the user is using an operating system that cannot handle IE 7 or IE 8 the user will be pointed to Firefox.s'),
    '#default_value' => variable_get('sevenUp_downloadLink', 1),
    '#type' => 'radios',
    '#options' => array(
      1 => t('Internet Explorer'),
      0 => t('Firefox'),
    ),
  );
  $form['sevenUp_showToAllBrowsers'] = array(
    '#title' => t('Show to all browsers'),
    '#description' => t('Would you like the message shown to all browsers, usually for testing purposes.'),
    '#default_value' => variable_get('sevenUp_showToAllBrowsers', 'false'),
    '#type' => 'radios',
    '#options' => $options,
  );
  $form['sevenup_black_plugin'] = array(
    '#title' => t('Use the Black plugin'),
    '#description' => t('Use the black theme plugin. This overrights your color settings. With this plugin you cannot disable closing the notification box.'),
    '#default_value' => variable_get('sevenup_black_plugin', 0),
    '#type' => 'radios',
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_init().
 */
function sevenup_init() {
  drupal_add_js(drupal_get_path('module', 'sevenup') .'/sevenup.0.3.js', 'module');
  $test_function = 'sevenUp.test(options);';
  if (variable_get('sevenup_black_plugin', 0)) {
    $test_function = 'sevenUp.plugin.black.test';
    drupal_add_js(drupal_get_path('module', 'sevenup') .'/sevenup_black.0.3.js');
  }
  
  drupal_add_js('$(document).ready(function(){
    var options = {  
      enableClosing: '. variable_get('sevenUp_enableClosing', 'true') .',
      enableQuitBuggingMe: '. variable_get('sevenUp_enableQuitBuggingMe', 'true') .',
      overlayColor: "'. variable_get('sevenUp_overlayColor', '#000000') .'",  
      lightboxColor: "'. variable_get('sevenUp_lightboxColor', '#ffffff') .'",
      borderColor: "'. variable_get('sevenUp_borderColor', '#6699ff') .'",
      '. (variable_get('sevenUp_downloadLink', 1) ? '' : 'downloadLink: "http://www.getfirefox.com",' ) .'
      overrideLightbox: false,
      lightboxHTML: null,
      showToAllBrowsers: '. variable_get('sevenUp_showToAllBrowsers', 'false') .'
    };
    '. $test_function .'(options);
  });', 'inline');
}