<?php

/**
 * @file sedermera_log.module
 * Main module file for the Sedermera Log module.
 */

/**
 * Implements hook_init().
 */
function sedermera_log_init() {
  $path = request_path();

  // Log the requested path and indicate if it was requested via AJAX or not.
  if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
    sedermera_log_watchdog('Path "@path" loaded via AJAX.', array('@path' => $path));
  }
  else {
    sedermera_log_watchdog('Path "@path" loaded.', array('@path' => $path));
  }
}

/**
 * The function used for logging.
 *
 * This is a wrapper around watchdog() which adds information about the current
 * user to the message. The function could be used by any other module, were
 * suitable.
 *
 * @see watchdog()
 *
 * @param string @message
 *   The message.
 * @param array $variables
 *   Variables to replace in the message.
 * @param int $severity
 *   Severity of the log message. See watchdog() for more information.
 */
function sedermera_log_watchdog($message, $variables = array(), $severity = WATCHDOG_NOTICE) {
  global $user;

  // Add information to the message.
  $message .= ' Current user: @user with session @session.';
  $variables['@user'] = $user->mail;
  $variables['@session'] = $user->sid;

  // Send to watchdog.
  watchdog('sedermera', $message, $variables, $severity);
}
