<?php

/**
 * @file sedermera_offer.module
 * Main module file for the Sedermera Offer module.
 */

/**
 * Implements hook_msnf_info_steps_alter().
 */
function sedermera_offer_msnf_info_steps_alter(&$steps_cached, $entity_type, $bundle, $form, $form_state = array()) {
  // Disable every step when editing an existing capital raising node.
  if ($entity_type == 'node' && $bundle == 'capital_raising' && !empty($form['node']->nid)) {
    $steps_cached = array();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_offer_form_capital_raising_node_form_alter(&$form, &$form_state) {
  if ($form['#node']->nid) {
    // Don't alter the form when editing an existing node, bail out.
    return;
  }

  // Add the offer display from the investors view as a prefix to the form. The
  // view is needed in order to filter among the investors. The view can't be
  // embedded as a subform within the node form, since this will break the AJAX
  // functionality. The reason is unknown, but that's just the way it is...
  if ($form_state['storage']['step'] == 'step_cap_rais_2') {
    $form['#prefix'] = views_embed_view('investors', 'offer_embed');
  }

  // Get the available investors from the database.
  $available_investors = db_query('SELECT id, title FROM {eck_investor}')->fetchAllKeyed();

  // Get the selected investors, based on the form values, and sort them
  // alphabetically.
  $selected_investors = isset($form_state['values']['investors']) ? array_intersect_key($available_investors, array_filter($form_state['values']['investors'])) : array();
  asort($selected_investors);

  // Add checkboxes for every available investor. This will be added to the
  // second step, and will get its values from the embedded view. See the
  // attached javascript for more information about what's going on.
  $form['investors'] = array(
    '#type' => 'checkboxes',
    '#options' => $available_investors,
    '#default_value' => array_keys($selected_investors),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'sedermera_offer') . '/sedermera_offer.js'
      ),
    ),
    '#prefix' => '<div style="display: none;">',
    '#suffix' => '</div>',
  );
  $form['#step_children']['investors'] =  'step_cap_rais_2';

  // Add elements that are required for the third step.
  if ($form_state['storage']['step'] == 'step_cap_rais_3') {
    // Build the node object based of the form values. This will be used to
    // generate the preview.
    $node = node_form_submit_build_node($form, $form_state);

    // Add the rendered node as a preview to the left fieldset. This fieldset will
    // be added to the third step.
    $form['preview_left'] = array(
      '#type' => 'fieldset',
      '#title' => 'Översikt',
    );
    $form['preview_left']['node'] = node_view($node);
    $form['#step_children']['preview_left'] =  'step_cap_rais_3';

    // Add checkboxes for every selected investor, which will be added to the
    // third step. This will be used as the confirmation page, where the user will
    // be able to deselect some of the investors before creating the transaction.
    $form['preview_right'] = array(
      '#type' => 'fieldset',
      '#title' => 'Investerare',
      '#description' => 'Följande investerare kommer att få utskicket:',
    );
    $form['preview_right']['selected_investors'] = array(
      '#type' => 'checkboxes',
      '#options' => $selected_investors,
      '#default_value' => array_keys($selected_investors),
    );
    $form['#step_children']['preview_right'] =  'step_cap_rais_3';
  }

  // Change the text of the submit button.
  $form['actions']['submit']['#value'] = 'Spara och skicka ut';
}


/**
 * Implements hook_node_insert().
 */
function sedermera_offer_node_insert($node) {
  if ($node->type != 'capital_raising' || empty($node->selected_investors)) {
    return;
  }

  // Create offer entities for each investor.
  foreach (array_filter($node->selected_investors) as $investor_id) {
    // Setup the values for the offer entity.
    $values = array(
      'type' => 'offer',
      'field_offer_cap_rais' => array(
        LANGUAGE_NONE => array(
          array('target_id' => $node->nid)
        ),
      ),
      'field_offer_investor' => array(
        LANGUAGE_NONE => array(
          array('target_id' => $investor_id)
        ),
      ),
    );

    // Create the offer, and save it.
    $offer = entity_create('offer', $values);
    entity_save('offer', $offer);
  }
}

/**
 * Implements hook_views_bulk_operations_form_alter().
 */
function sedermera_offer_views_bulk_operations_form_alter(&$form, &$form_state, $vbo) {
  // Remove the action selection and submit button for the VBO form for the
  // investors embeded offer display.
  if ($vbo->view->name == 'investors' && $vbo->view->current_display == 'offer_embed') {
    $form['select']['#access'] = FALSE;
    $form['actions']['#access'] = FALSE;
  }
}
