<?php

/**
 * @file
 * Installation settings for Fancybox module.
 */

/**
 * Implementation of hook_install()
 */
function fancybox_install() {
  _set_fancybox_files();
}

/**
 * Implementation of hook_uninstall()
 */
function fancybox_uninstall() {
  // Delete variables.
  $variables = array('fancybox_path', 'fancybox_settings', 'fancybox_files');
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}