<?php

/**
 * @file sedermera_paths.module
 * Main module file for the Sedermera Paths module.
 */

/**
 * Implements hook_path_insert().
 */
function sedermera_paths_path_insert($path) {
  // Load the menu router item for this source path.
  $router = menu_get_item($path['source']);

  // Make sure that we should create aliases for this type of entity.
  switch ($router['page_callback']) {
    case 'eck__entity__view':
      // Verify that the ECK entity type is an investor.
      if ($router['page_arguments'][0] != 'investor') {
        return;
      }
      break;

    case 'node_page_view':
      // Verify that the node type is capital raising or company.
      if (!in_array($router['page_arguments'][0]->type, array('capital_raising', 'company'))) {
        return;
      }
      break;

    default:
      // We shouldn't create aliases for this router item.
      return;
  }

  // Fetch menu routes which starts with the router path.
  $query = db_select('menu_router', 'router');
  $query->addField('router', 'path');
  $query->condition('path', '^' . $router['path'] . '\/', 'REGEXP');

  // Add an alias for the paths that were  found.
  foreach ($query->execute() as $row) {
    // Remove the router path from the path that was found in order to generate
    // an alias for the subpath. The subpath for node/%/edit will become /edit,
    // and so on.
    $subpath = str_replace($router['path'], '', $row->path);

    // Create an alias for this subpath if it doesn't contain any arguments.
    if (!strstr($subpath, '%')) {
      $alias = array(
        'source' => $path['source'] . $subpath,
        'alias' => $path['alias'] . $subpath,
        'language' => $path['language'],
      );
      path_save($alias);
    }
  }
}
