<?php

/**
 * @file sedermera_disclaimer.module
 * Main module file for the Sedermera Disclaimer module.
 */

/**
 * Implements hook_user_login().
 */
function sedermera_disclaimer_user_login(&$edit, $account) {
  // dprint_r($edit);

  // dprint_r($account);
  // die;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function sedermera_disclaimer_form_user_login_alter(&$form, &$form_state) {
  $form['#submit'][] = 'sedermera_disclaimer_user_login_submit';
}

/**
 * Submit callback for the user login form.
 */
function sedermera_disclaimer_user_login_submit(&$form, &$form_state) {
  // Redirect the user to the front page.
  $form_state['redirect'] = 'dokument/lista';

  // dprint_r($form_state);
  // die;
}
