<?php

/**
 * @file sedermera_company.module
 * Main module file for the Sedermera Company module.
 */

/**
 * Implements hook_node_view().
 */
function sedermera_company_node_view($node, $view_mode, $langcode) {
  // Bail out if this isn't a company node that's viewed on its own page.
  if ($node->type != 'company' || $view_mode != 'full' || !node_is_page($node)) {
    return;
  }

  // Set the active menu trail based on the archived state.
  menu_tree_set_path('main-menu', 'kundbolag');
}

/**
 * Implements hook_node_prepare().
 */
function sedermera_company_node_prepare($node) {
  // Bail out if this isn't an existing company node.
  if ($node->type != 'company' || !$node->nid) {
    return;
  }

  // Set the active menu trail based on the archived state.
  menu_tree_set_path('main-menu', 'kundbolag');
}
