<?php
/**
 * @file
 * Easily switch between different environments for your site. This will
 * automatically enable/disable modules and set various variables.
 */

define('TADAA_ENVIRONMENT', variable_get('tadaa_environment'));
define('TADAA_BASE_PATH', drupal_get_path('module', 'tadaa'));
define('TADAA_THEME_PATH', drupal_get_path('module', 'tadaa') . '/theme');

/**
 * Implements hook_permission().
 */
function tadaa_permission() {
  return array('use tadaa' => array(
    'title' => t('Use Tadaa!'),
    'description' => t('Switch environments using the Tadaa! toolbar'),
    'restrict access' => TRUE,
  ));
}

/**
 * Implements hook_menu().
 */
function tadaa_menu() {
  // Included files.
  $callback_file = 'tadaa.callbacks.inc';
  $page_file = 'tadaa.pages.inc';

  // Checks the state for the selected environment.
  $items['tadaa/environment/check'] = array(
    'page callback' => 'tadaa_check_environment',
    'access arguments' => array('use tadaa'),
    'file' => $callback_file,
    'type' => MENU_CALLBACK,
  );
  // Checks the state for individual modules.
  $items['tadaa/module/%/check'] = array(
    'page callback' => 'tadaa_check_module',
    'page arguments' => array(2),
    'access arguments' => array('use tadaa'),
    'file' => $callback_file,
    'type' => MENU_CALLBACK,
  );
  // Checks the state for individual variables.
  $items['tadaa/variable/%/check'] = array(
    'page callback' => 'tadaa_check_variable',
    'page arguments' => array(2),
    'access arguments' => array('use tadaa'),
    'file' => $callback_file,
    'type' => MENU_CALLBACK,
  );
  
  // Checks the state for the selected environment.
  $items['admin/config/development/tadaa'] = array(
    'title' => 'Tadaa!',
    'description' => 'View the status for the current environment.',
    'page callback' => 'tadaa_module_status_page',
    'access arguments' => array('use tadaa'),
    'file' => $page_file,
  );
  // Checks the state for individual modules.
  $items['admin/config/development/tadaa/modules'] = array(
    'title' => 'Modules',
    'access arguments' => array('use tadaa'),
    'file' => $page_file,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  // Checks the state for individual variables.
  $items['admin/config/development/tadaa/variables'] = array(
    'title' => 'Variables',
    'page callback' => 'tadaa_variable_status_page',
    'access arguments' => array('use tadaa'),
    'file' => $page_file,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function tadaa_theme($existing, $type, $theme, $path) {
  return array(
    'tadaa_toolbar' => array(
      'template' => 'tadaa-toolbar',
      'variables' => array(
        'environments_form' => NULL,
        'email_form' => NULL,
      ),
      'path' => TADAA_THEME_PATH,
    ),
  );
}

/**
 * Implements hook_init().
 */
function tadaa_init() {
  if (!user_access('use tadaa')) {
    // The user doesn't have access, exit early.
    return;
  }
  
  // Add some javascript settings.
  $settings['selectedEnvironment'] = TADAA_ENVIRONMENT;
  $settings['modules'] = tadaa_get_modules();
  $settings['variables'] = tadaa_get_variables();
  drupal_add_js(array('tadaa' => $settings), 'setting');
  
  // Add our JS and CSS file.
  drupal_add_js(TADAA_BASE_PATH . '/tadaa.js');
  drupal_add_css(TADAA_THEME_PATH . '/tadaa.css');
}

/**
 * Implements hook_page_alter().
 */
function tadaa_page_alter(&$page) {
  if (!user_access('use tadaa')) {
    // The user doesn't have access, exit early.
    return;
  }
  
  // Include the file with our callbacks.
  require TADAA_BASE_PATH . '/tadaa.callbacks.inc';
  
  // Get the environments form.
  $variables['environments_form'] = drupal_get_form('tadaa_environment_form');

  // Get the email form, if Reroute email is enabled.
  $variables['email_form'] = module_exists('reroute_email') ? drupal_get_form('tadaa_email_form') : FALSE;
  
  // Add the toolbar to the bottom region.
  $page['page_bottom']['tadaa'] = array(
    '#type' => 'markup',
    '#markup' => theme('tadaa_toolbar', $variables),
  );
}

/**
 * Implements hook_form().
 *
 * This is the form that's used for switching environments. It's added to the
 * toolbar.
 */
function tadaa_environment_form($form, &$form_state) {
  // Create a select list.
  $form['environment'] = array(
    '#type' => 'select',
    '#title' => t('Current environment'),
    '#ajax' => array(
      'callback' => 'tadaa_set_environment',
      'progress' => array(
        'type' => 'throbber',
        'message' => '',
      ),
    ),
  );
  
  if (TADAA_ENVIRONMENT) {
    // Set the current environment as the default.
    $form['environment']['#default_value'] = TADAA_ENVIRONMENT;
  }
  else {
    // No environment has been chosen, add an option that clearly shows that no
    // environment has been chosen.
    $form['environment']['#options'][''] = t('- None -');
    $form['environment']['#default_value'] = '';
  }
  
  // Add each environment as an option to the select list.
  $environments = tadaa_get_environments();
  foreach ($environments as $environment => $configuration) {
    $form['environment']['#options'][$environment] = $configuration['name'];
  }

  return $form;
}

/**
 * AJAX callback that sets a new environment.
 *
 * This will activate the modules for the specified environment, and set it's
 * variables to there configured values.
 */
function tadaa_set_environment($form, &$form_state) {
  // The selected environment.
  $environment = $form_state['values']['environment'];

  if (!$environment) {
    // No environment specified, exit early.
    return;
  }

  // Get every module. The modules for this environment will be marked as
  // enabled.
  $modules = tadaa_get_modules($environment);

  // Build one array for the modules that should be enabled, and one for the
  // ones that should be disabled.
  $enable = array();
  $disable = array();
  foreach ($modules as $module => $status) {
    if ($status) {
      // Enabled module.
      $enable[] = $module;
    }
    else {
      // Disabled module.
      $disable[] = $module;
    }
  }

  // Enable and disable the modules.
  $test = module_enable($enable);
  module_disable($disable);

  // Get the variables for this environment, and set their values.
  $variables = tadaa_get_variables($environment);
  foreach ($variables as $variable => $value) {
    variable_set($variable, $value);
  }
  
  // Set the specified environment as the currently active one and flush all
  // caches.
  variable_set('tadaa_environment', $environment);
  drupal_flush_all_caches();
}

/**
 * Implements hook_form().
 *
 * This is the form that's used for setting an email address for Reroute email.
 * It's added to the toolbar if Reroute email is enabled.
 */
function tadaa_email_form($form, &$form_state) {
  // Create a textarea.
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Reroute emails to'),
    '#default_value' => variable_get('reroute_email_address', ''),
    '#ajax' => array(
      'callback' => 'tadaa_set_email',
      'progress' => array(
        'type' => 'throbber',
        'message' => '',
      ),
    ),
  );

  return $form;
}

/**
 * AJAX callback that sets the Reroute email address.
 *
 * @see http://drupal.org/project/reroute_email
 */
function tadaa_set_email($form, &$form_state) {
  $email = $form_state['values']['email'];
  if ($email) {
    variable_set('reroute_email_address', $email);
  }
  else {
    variable_del('reroute_email_address');
  }
}

/**
 * Gets the environments and the configurations.
 *
 * The modules will only be affected if they actually exists. This is handled
 * when they are enabled/disabled.
 *
 * TODO: Make this configurable through the UI. I belive the best approache is
 * to enable users to create custom environments, and configure them as needed.
 *
 * @return
 *  An associative array, where each element is an environment, and the key is
 *  used to identify the environment.
 *  - name: The human readable name of the environment.
 *  - modules: An array of modules that should be enabled only when this
 *    environment is in use.
 *  - variables: An array of variables, where the key is the name of the
 *    variable, and the value is the value of the variable that should be set
 *    when this environment is in use.
 */
function tadaa_get_environments() {
  $environments = array(
    'dev' => array(
      'name' => t('Development'),
      'modules' => array(
        'context_ui',
        'devel',
        'devel_generate',
        'devel_node_access',
        'reroute_email',
        'rules_admin',
        'themekey_ui',
        'views_ui',
      ),
      'variables' => array(
        'cache' => 0,
        'preprocess_js' => 0,
        'preprocess_css' => 0,
        'jquery_update_compression_type' => 'none',
      ),
    ),
    'staging' => array(
      'name' => t('Staging'),
      'modules' => array(
        'context_ui',
        'reroute_email',
        'rules_admin',
        'themekey_ui',
        'views_ui',
      ),
      'variables' => array(
        'cache' => 1,
        'preprocess_js' => 1,
        'preprocess_css' => 1,
        'jquery_update_compression_type' => 'min',
      ),
    ),
    'prod' => array(
      'name' => t('Production'),
      'modules' => array(
        'backup_migrate',
        'googleanalytics',
      ),
      'variables' => array(
        'cache' => 1,
        'preprocess_js' => 1,
        'preprocess_css' => 1,
        'jquery_update_compression_type' => 'min',
      ),
    ),
  );

  return $environments;
}

/**
 * Gets every configured module and their state.
 *
 * @param $active_environment
 *  A string indicating which environment we are considiring the active
 *  environment. If left empty, modules will be returned with the state set to
 *  FALSE.
 *
 * @return
 *  An associative array where each key is the name of the module, and the value
 *  is the state of the module, according to the $environment param.
 */
function tadaa_get_modules($active_environment = NULL) {
  // Build an array of every configured module. Consider every module to be
  // disabled for now.
  $environments = tadaa_get_environments();
  foreach ($environments as $environment) {
    foreach ($environment['modules'] as $module) {
      $modules[$module] = FALSE;
    }
  }
  
  // If we have an active environment, set each module of this environment to be
  // active.
  if ($active_environment) {
    foreach ($environments[$active_environment]['modules'] as $module) {
      $modules[$module] = TRUE;
    }
  }
  
  // Remove modules that doesn't exist at all.
  foreach ($modules as $module => $configuration) {
    // Scan these directories.
    $directories = array(
      DRUPAL_ROOT . '/sites',
      DRUPAL_ROOT . '/modules',
      DRUPAL_ROOT . '/profiles',
    );
    foreach ($directories as $directory) {
      $file = file_scan_directory($directory, '/^' . $module . '\.module$/');
      if (count($file)) {
        // The module was found, stop searching.
        continue 2;
      }
    }
    // The module wasn't found, remove it from the array.
    unset($modules[$module]);
  }
  
  // Sort the modules by their name before return the array.
  ksort($modules);
  return $modules;
}

/**
 * Gets the configured variables for a specific environment.
 *
 * @param $active_environment
 *  A string indicating which environment we are considiring the active
 *  environment. If left empty, every configured variable will be returned.
 */
function tadaa_get_variables($environment = NULL) {
  $environments = tadaa_get_environments();
  if ($environment) {
    // An environment has been specified, get the variables for that
    // environment.
    foreach ($environments[$environment]['variables'] as $variable => $value) {
      $variables[$variable] = $value;
    }
  }
  else {
    // No environment has been specified, return every configured variable.
    foreach ($environments as $environment) {
      foreach ($environment['variables'] as $variable => $value) {
        $variables[$variable] = $value;
      }
    }
  }

  // Sort the variables by their name before returning them.
  ksort($variables);
  return $variables;
}
